name: "PHP Linting"

on:
  push:
  pull_request:
    branches: [main]

jobs:
  phplint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: "laravel-pint"
        uses: aglipanci/laravel-pint-action@v2
        with:
          preset: laravel
          verboseMode: true
          testMode: true
          configPath: pint.json
